const state={role:"admin",page:"dashboard"};
const names={admin:"Administrador",teacher:"Docente",student:"Estudante"};
const menus={
 admin:[["dashboard","Visão geral"],["users","Usuários"],["courses","Cursos"],["disciplines","Disciplinas"],["materials","Materiais didáticos"]],
 teacher:[["dashboard","Visão geral"],["disciplines","Minhas disciplinas"],["materials","Materiais didáticos"]],
 student:[["dashboard","Visão geral"],["disciplines","Minhas disciplinas"]]
};
const main=document.getElementById("main");
document.getElementById("loginForm").onsubmit=e=>{e.preventDefault();state.role=document.getElementById("role").value;state.page="dashboard";document.getElementById("login").classList.add("hidden");document.getElementById("system").classList.remove("hidden");render()};
document.getElementById("logout").onclick=()=>{document.getElementById("system").classList.add("hidden");document.getElementById("login").classList.remove("hidden")};
function render(){document.getElementById("roleName").textContent=names[state.role];renderNav();renderPage()}
function renderNav(){document.getElementById("nav").innerHTML=menus[state.role].map(x=>`<button class="nav ${state.page===x[0]?"active":""}" data-p="${x[0]}">${x[1]}</button>`).join("");document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{state.page=b.dataset.p;render()})}
function head(t,s){return `<div class="head"><div><h2>${t}</h2><p>${s}</p></div></div>`}
function metric(l,n,i){return `<div class="card metric"><div><div class="muted">${l}</div><div class="num">${n}</div></div><div class="icon">${i}</div></div>`}
function card(t,s,n){return `<div class="card course"><span class="badge">Disciplina</span><h3>${t}</h3><p class="muted">${s}</p><p><b>${n}</b></p><button class="primary" onclick="course('${t}')">Acessar disciplina</button></div>`}
function renderPage(){({dashboard,users,courses,disciplines,materials}[state.page]||dashboard)()}
function dashboard(){
 let cards=state.role==="admin"?metric("Usuários","24","US")+metric("Cursos","4","CU")+metric("Disciplinas","12","DI"):metric("Disciplinas","3","DI")+metric("Materiais","18","MT")+metric("Conteúdos externos","9","EX");
 main.innerHTML=head("Visão geral",state.role==="admin"?"Administração do ambiente de aprendizagem.":"Conteúdos disponíveis para suas disciplinas.")+`<div class="grid">${cards}</div><h3 class="section">${state.role==="admin"?"Atividade do ambiente":"Minhas disciplinas"}</h3><div class="grid grid2">${card("Desenvolvimento Web","Tecnologias Full Stack","8 materiais")}${card("Banco de Dados","Modelagem e SQL","5 materiais")}${card("Engenharia de Software","Projeto e testes","5 materiais")}</div>`;
}
function users(){main.innerHTML=head("Usuários","Cadastro e gerenciamento dos usuários do ambiente.")+`<div class="card table"><table><thead><tr><th>Nome</th><th>Perfil</th><th>E-mail</th><th>Status</th></tr></thead><tbody><tr><td>Maria Oliveira</td><td>Docente</td><td>maria@edulms.local</td><td><span class="badge success">Ativo</span></td></tr><tr><td>João Santos</td><td>Estudante</td><td>joao@edulms.local</td><td><span class="badge success">Ativo</span></td></tr><tr><td>Administrador</td><td>Administrador</td><td>admin@edulms.local</td><td><span class="badge success">Ativo</span></td></tr></tbody></table></div>`}
function courses(){main.innerHTML=head("Cursos","Gerenciamento dos cursos disponíveis no ambiente.")+`<div class="grid">${card("Especialização Full Stack","Formação em desenvolvimento web","5 disciplinas")}${card("Tecnologia Educacional","Recursos digitais para educação","4 disciplinas")}${card("Desenvolvimento Web","Fundamentos e aplicações web","3 disciplinas")}</div>`}
function disciplines(){main.innerHTML=head(state.role==="student"?"Minhas disciplinas":"Disciplinas","Organização das disciplinas e acesso aos conteúdos.")+`<div class="card table"><table><thead><tr><th>Disciplina</th><th>Curso</th><th>Responsável</th><th>Materiais</th><th>Acesso</th></tr></thead><tbody><tr><td>Desenvolvimento Web</td><td>Especialização Full Stack</td><td>Maria Oliveira</td><td>8</td><td><span class="badge success">Disponível</span></td></tr><tr><td>Banco de Dados</td><td>Especialização Full Stack</td><td>Maria Oliveira</td><td>5</td><td><span class="badge success">Disponível</span></td></tr><tr><td>Engenharia de Software</td><td>Especialização Full Stack</td><td>João Costa</td><td>5</td><td><span class="badge success">Disponível</span></td></tr></tbody></table></div>`}
function materials(){main.innerHTML=head("Materiais didáticos","Conteúdos organizados por disciplina e incorporados a partir de fontes externas.")+`<div class="grid grid2">${mat("HTML5 e estrutura de páginas","Desenvolvimento Web","Documento externo")}${mat("Introdução ao Node.js","Desenvolvimento Web","Vídeo externo")}${mat("Modelagem relacional","Banco de Dados","Documento externo")}${mat("Testes de software","Engenharia de Software","Vídeo externo")}</div><h3 class="section">Conteúdo incorporado</h3><div class="card"><div class="embed"><div><b>Conteúdo externo incorporado</b>Área reservada para vídeo, áudio ou documento hospedado externamente.<br>O protótipo não realiza upload de arquivos.</div></div></div>`}
function mat(t,d,k){return `<div class="card material"><div class="mi">MT</div><div><h4>${t}</h4><p>${d}</p><span class="badge">${k}</span></div></div>`}
function course(t){main.innerHTML=head(t,"Materiais didáticos da disciplina.")+`<div class="detail"><div><div class="hero"><h3>${t}</h3><p>Conteúdos organizados para apoio às atividades de ensino e aprendizagem.</p></div><h3 class="section">Materiais</h3><div class="card">${mat("Material introdutório",t,"Documento externo")}</div><br><div class="card">${mat("Aula em vídeo",t,"Vídeo externo")}</div></div><div class="card"><h3>Informações</h3><p><b>Responsável:</b> Docente</p><p><b>Materiais:</b> disponíveis</p><p><b>Acesso:</b> conforme vínculo com a disciplina</p></div></div>`}
render();
